In [1]:
import numpy as np

**Objective:
You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create,
 modify, and analyze the data efficiently without using any external libraries.

 **Project Description:
 A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution
 to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing
 modifications, and analyzing patterns — all using NumPy.

 Project Tasks:

1. **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.

In [ ]:
#1 data creation

students=np.array([1,2,3,4])
subjects=np.array([1,2,3])
marks=np.array([[80,40,32],[70,82,36],[92,47,75],[85,32,47]])
marks

array([[80, 40, 32],
       [70, 82, 36],
       [92, 47, 75],
       [85, 32, 47]])

In [ ]:
marks[3][2]

np.int64(47)

2 .**Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.

In [ ]:
#2  data exploration

students.ndim
subjects.ndim
marks.ndim

2

In [ ]:
students.size
subjects.size
marks.size


12

In [ ]:
students.shape
subjects.shape
marks.shape


(4, 3)

3.** Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.

In [ ]:
#3 data transformation

flat_marks=marks.flatten()
flat_marks

array([80, 40, 32, 70, 82, 36, 92, 47, 75, 85, 32, 47])

In [ ]:
reshaped_marks=marks.reshape(3,4)
reshaped_marks


array([[80, 40, 32, 70],
       [82, 36, 92, 47],
       [75, 85, 32, 47]])

In [ ]:
transposed=marks.T
transposed

array([[80, 70, 92, 85],
       [40, 82, 47, 32],
       [32, 36, 75, 47]])

4. **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset

In [ ]:
#4 data combination

split_marks=np.split(marks,2)
split_marks

[array([[80, 40, 32],
        [70, 82, 36]]),
 array([[92, 47, 75],
        [85, 32, 47]])]

In [ ]:
split_subjects=np.split(subjects,3)
split_subjects

[array([1]), array([2]), array([3])]

In [ ]:
split_students=np.split(students,2)
split_students

[array([1, 2]), array([3, 4])]

5. Data Modification:*Apply operations to update marks, remove data, or identify unique information.

In [ ]:
#5 data modification
#updating
marks[1,0]=85
marks


array([[80, 40, 32],
       [85, 82, 36],
       [92, 47, 75],
       [85, 32, 47]])

In [ ]:
marks[3,2]=0
marks

array([[80, 40, 32],
       [85, 82, 36],
       [92, 47, 75],
       [85, 32,  0]])

In [ ]:
#removing data
marks=np.delete(students,2)
marks


array([1, 2, 4])

In [ ]:
#unique
unique_marks=np.unique(marks)
unique_marks

array([1, 2, 4])

6. *Data Type Handling:*Demonstrate how the same data can exist in different data types and how changes affect results.

In [8]:
marks_float=marks.astype(dtype=float)
print(marks_float)

NameError: name 'marks' is not defined

7. *Copy and View Behavior:*Show the difference between creating a full copy of an array and creating a view of the same data.

In [9]:
marks_view=marks.view()
marks_view[0,0]=100
print("viewed msrks:",marks_view)
print("original:",marks)

NameError: name 'marks' is not defined